In [37]:
data=pd.read_excel('data/2018_공연시설별+통계목록.xls', header=3)
data=data.fillna(method='ffill')
data.columns=['시설명','공연홀','좌석수','공연건수','개막편수','상연횟수','예매수']

In [43]:
location=pd.read_excel('data/공연장등록현황_2018.xlsx',header=2)
location=location.loc[:,['시도별','시군구','시설명']]
location.dropna(axis=0, inplace=True)

In [46]:
location=pd.read_excel('./DB공연장.xls', header=3)

In [47]:
location=location.dropna(axis=0)

In [48]:
location=location.rename(columns={'시설명(링크)':'시설명','Unnamed: 9':'시군구'})
location=location.loc[:,['시설특성','지역','시군구','주소','시설명']]

In [49]:
df=pd.merge(data,location,on='시설명', how='inner')

In [50]:
df

,시설명,공연홀,좌석수,공연건수,개막편수,상연횟수,예매수,시설특성,지역,시군구,주소
0,예술의전당,콘서트홀,2527,155,155,157,176839,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
1,예술의전당,오페라극장,2283,19,19,83,88155,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
2,예술의전당,IBK챔버홀,600,200,200,201,65978,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
3,예술의전당,CJ 토월극장,1004,15,15,189,55309,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
4,예술의전당,리사이틀홀,354,181,181,181,48292,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
...,...,...,...,...,...,...,...,...,...,...,...
1116,천마아트센터,챔버홀,510,0,0,0,0,민간(대학로 외),경북,경산시,경상북도 경산시 대학로 280 (대동)
1117,천마아트센터,합계,2399,1,1,1,0,민간(대학로 외),경북,경산시,경상북도 경산시 대학로 280 (대동)
1118,청춘나비아트홀,합계,80,1,1,1,0,민간(대학로 외),부산,수영구,부산광역시 수영구 수영로 657 (광안동)
1119,최순우 옛집,합계,30,1,1,1,0,기타(비공연장),서울,성북구,서울특별시 성북구 성북로15길 9 (성북동)
1120,해피씨어터,합계,219,2,1,67,-18,민간(대학로),서울,종로구,서울특별시 종로구 대학로10길 5 (동숭동)

In [86]:
df.to_csv("stage_location.csv")

In [53]:
df=pd.read_csv('./stage_location.csv',index_col=0 )
df

,시설명,공연홀,좌석수,공연건수,개막편수,상연횟수,예매수,시설특성,지역,시군구,주소
0,예술의전당,콘서트홀,2527,155,155,157,176839,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
1,예술의전당,오페라극장,2283,19,19,83,88155,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
2,예술의전당,IBK챔버홀,600,200,200,201,65978,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
3,예술의전당,CJ 토월극장,1004,15,15,189,55309,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
4,예술의전당,리사이틀홀,354,181,181,181,48292,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
...,...,...,...,...,...,...,...,...,...,...,...
1116,천마아트센터,챔버홀,510,0,0,0,0,민간(대학로 외),경북,경산시,경상북도 경산시 대학로 280 (대동)
1117,천마아트센터,합계,2399,1,1,1,0,민간(대학로 외),경북,경산시,경상북도 경산시 대학로 280 (대동)
1118,청춘나비아트홀,합계,80,1,1,1,0,민간(대학로 외),부산,수영구,부산광역시 수영구 수영로 657 (광안동)
1119,최순우 옛집,합계,30,1,1,1,0,기타(비공연장),서울,성북구,서울특별시 성북구 성북로15길 9 (성북동)
1120,해피씨어터,합계,219,2,1,67,-18,민간(대학로),서울,종로구,서울특별시 종로구 대학로10길 5 (동숭동)

In [54]:
df.loc[df['지역'] == '서울',:]

,시설명,공연홀,좌석수,공연건수,개막편수,상연횟수,예매수,시설특성,지역,시군구,주소
0,예술의전당,콘서트홀,2527,155,155,157,176839,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
1,예술의전당,오페라극장,2283,19,19,83,88155,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
2,예술의전당,IBK챔버홀,600,200,200,201,65978,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
3,예술의전당,CJ 토월극장,1004,15,15,189,55309,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
4,예술의전당,리사이틀홀,354,181,181,181,48292,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
...,...,...,...,...,...,...,...,...,...,...,...
1107,경희대학교 평화의전당,합계,4500,1,1,2,0,민간(대학로 외),서울,동대문구,서울특별시 동대문구 경희대로6길 7-13 (회기동)
1111,마포중앙도서관,합계,396,1,1,1,0,공공(기타),서울,마포구,서울특별시 마포구 성산로 128 (성산동)
1112,북쌔즈 복합문화공간,합계,0,1,1,1,0,민간(대학로 외),서울,강남구,서울특별시 강남구 테헤란로 311 (역삼동)
1119,최순우 옛집,합계,30,1,1,1,0,기타(비공연장),서울,성북구,서울특별시 성북구 성북로15길 9 (성북동)
1120,해피씨어터,합계,219,2,1,67,-18,민간(대학로),서울,종로구,서울특별시 종로구 대학로10길 5 (동숭동)

In [56]:
df.groupby('지역')['좌석수'].sum()

지역
강원     30302
경기    112192
경남     33954
경북     35614
광주     21174
대구     42736
대전     19643
부산     64029
서울    535946
세종      2520
울산     12436
인천     18651
전남     17300
전북     37230
제주     10473
충남     20103
충북     16931
Name: 좌석수, dtype: int64

In [67]:
show=pd.read_excel('./DB검색_공연DB.xls', index_col=0,header=4, names = ['No','공연명','장르', '시작일','종료일','시설명','공연장','좌석수','제작'])

In [72]:
show

,공연명,장르,시작일,종료일,시설명,공연장,좌석수,제작
No,,,,,,,,
1,스크루지의 크리스마스 파티 [수원],뮤지컬,2018.11.24,2019.01.01,KBS 수원아트홀,KBS 수원아트홀,200,"극단 꿈의 공작소, 극단 꿈의 공작소"
2,공룡 애니멀쇼 [동두천],뮤지컬,2018.12.01,2018.12.02,동두천시민회관,동두천시민회관,480,주니엔터테인먼트
3,롯데콘서트홀 송년·제야음악회,클래식,2018.12.30,2018.12.31,롯데콘서트홀,롯데콘서트홀,"2,036","롯데문화재단, 롯데문화재단"
4,노리야 학교가자 [수원],뮤지컬,2018.10.20,2018.11.18,KBS 수원아트홀,KBS 수원아트홀,200,"극단 꿈의 공작소, 극단 꿈의 공작소, 극단 꿈의 공작소"
5,비보이를 사랑한 발레리나 [구미],뮤지컬,2018.12.25,2018.12.25,구미시문화예술회관,대공연장,"1,211",(주)쇼봄(쇼비보이)
...,...,...,...,...,...,...,...,...
4472,쿵 페스티벌,뮤지컬,2012.04.17,2018.12.31,SJ비보이극장(구. 비보이전용극장),SJ비보이극장(구. 비보이전용극장),356,(주)에스제이비보이즈
4473,극적인 하룻밤,연극,2014.09.26,2019.02.24,바탕골소극장,바탕골소극장,200,"(주)연우무대, (주)레드앤블루(구. 악어컴퍼니)"
4474,작업의 정석 1탄,연극,2015.01.01,오픈런,"순위아트홀1관 [대학로], 순위아트홀(구. 네오아트홀) [강남]",순위아트홀1관 [대학로],221,(주)네오프로덕션
4475,수상한 흥신소 1탄 [대학로],연극,2015.03.01,2018.03.18,내유외강씨어터(구. 익스트림씨어터 1관),내유외강씨어터(구. 익스트림씨어터 1관),177,익스트림플레이
4476,페인터즈 [종로],뮤지컬,2015.01.01,오픈런,서울극장,페인터즈히어로 전용관,488,(주)펜타토닉/액션드로잉 히어로

In [138]:
show[show['시설명'].str.contains('구미시문화예술회관')]

,공연명,장르,시작일,종료일,시설명,공연장,좌석수,제작
No,,,,,,,,
5,비보이를 사랑한 발레리나 [구미],뮤지컬,2018.12.25,2018.12.25,구미시문화예술회관,대공연장,"1,211",(주)쇼봄(쇼비보이)

In [93]:
genre=show.groupby('시설명')['장르'].unique()

In [102]:
genre=genre.to_frame()

AttributeError: 'DataFrame' object has no attribute 'to_frame'

In [155]:
genre

                                     장르
시설명
(재)경기문화재단                          [연극]
(재)영화의전당                [오페라, 뮤지컬, 클래식]
2001 아울렛키즈홀 [수원남문]                [뮤지컬]
3.15아트센터             [클래식, 뮤지컬, 무용, 연극]
30스튜디오 (폐관)                        [연극]
...                                 ...
홍익대 대학로 아트센터                  [연극, 뮤지컬]
효로민락소극장                            [연극]
효천아트센터 그라운드씬                       [연극]
후용공연예술센터                           [연극]
흰물결아트센터                  [클래식, 뮤지컬, 무용]

[611 rows x 1 columns]

In [109]:
from sklearn.preprocessing import MultiLabelBinarizer
s=genre['장르']
mlb = MultiLabelBinarizer()

genres=pd.DataFrame(mlb.fit_transform(s),columns=mlb.classes_, index=genre.index)

In [121]:
genres.reset_index(inplace=True)

In [157]:
genres.to_csv('genres.csv')

In [112]:
df

,시설명,공연홀,좌석수,공연건수,개막편수,상연횟수,예매수,시설특성,지역,시군구,주소
0,예술의전당,콘서트홀,2527,155,155,157,176839,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
1,예술의전당,오페라극장,2283,19,19,83,88155,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
2,예술의전당,IBK챔버홀,600,200,200,201,65978,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
3,예술의전당,CJ 토월극장,1004,15,15,189,55309,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
4,예술의전당,리사이틀홀,354,181,181,181,48292,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동)
...,...,...,...,...,...,...,...,...,...,...,...
1116,천마아트센터,챔버홀,510,0,0,0,0,민간(대학로 외),경북,경산시,경상북도 경산시 대학로 280 (대동)
1117,천마아트센터,합계,2399,1,1,1,0,민간(대학로 외),경북,경산시,경상북도 경산시 대학로 280 (대동)
1118,청춘나비아트홀,합계,80,1,1,1,0,민간(대학로 외),부산,수영구,부산광역시 수영구 수영로 657 (광안동)
1119,최순우 옛집,합계,30,1,1,1,0,기타(비공연장),서울,성북구,서울특별시 성북구 성북로15길 9 (성북동)
1120,해피씨어터,합계,219,2,1,67,-18,민간(대학로),서울,종로구,서울특별시 종로구 대학로10길 5 (동숭동)

In [152]:
df1=pd.merge(df,genres,on='시설명', how='inner')

In [153]:
df1

,시설명,공연홀,좌석수,공연건수,개막편수,상연횟수,예매수,시설특성,지역,시군구,주소,국악,무용,뮤지컬,복합,연극,오페라,클래식
0,예술의전당,콘서트홀,2527,155,155,157,176839,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동),1,1,1,1,1,1,1
1,예술의전당,오페라극장,2283,19,19,83,88155,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동),1,1,1,1,1,1,1
2,예술의전당,IBK챔버홀,600,200,200,201,65978,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동),1,1,1,1,1,1,1
3,예술의전당,CJ 토월극장,1004,15,15,189,55309,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동),1,1,1,1,1,1,1
4,예술의전당,리사이틀홀,354,181,181,181,48292,국립,서울,서초구,서울특별시 서초구 남부순환로 2406 (서초동),1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,천마아트센터,챔버홀,510,0,0,0,0,민간(대학로 외),경북,경산시,경상북도 경산시 대학로 280 (대동),0,0,0,0,0,0,1
1100,천마아트센터,합계,2399,1,1,1,0,민간(대학로 외),경북,경산시,경상북도 경산시 대학로 280 (대동),0,0,0,0,0,0,1
1101,청춘나비아트홀,합계,80,1,1,1,0,민간(대학로 외),부산,수영구,부산광역시 수영구 수영로 657 (광안동),0,0,0,0,1,0,0
1102,최순우 옛집,합계,30,1,1,1,0,기타(비공연장),서울,성북구,서울특별시 성북구 성북로15길 9 (성북동),0,0,0,0,0,0,1
1103,해피씨어터,합계,219,2,1,67,-18,민간(대학로),서울,종로구,서울특별시 종로구 대학로10길 5 (동숭동),0,0,0,0,1,0,0

In [151]:
genres=genres.astype(str).stack().str.strip().unstack()